module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.bulkInsert(
      'guests',
      [
        {
          family_id: 1,
          name: 'Alessandra Pardo da Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 1,
          name: 'Edvaldo Raimundo Nazare da Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 2,
          name: 'Anderson de Souza Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 2,
          name: 'Raimundo Nonato da Silva Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 2,
          name: 'Claudiana Nascimeno da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 2,
          name: 'Alexsandro de Souza Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 2,
          name: 'Maria Alice de Souza Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 3,
          name: 'Leticia da Silva Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 4,
          name: 'Ariane da Silva Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 4,
          name: 'Alex de Barros Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 4,
          name: 'Ágata da Silva Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 4,
          name: 'Asaph da Silva Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Vilson Farias da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Francilene de Abreu Carvalho',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Isabel Lídia Batista da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Rodrigo Matos Batalha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Isaias Nilson Batista da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 5,
          name: 'Beatriz Rocha da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 7,
          name: 'Franklin William Camara Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 7,
          name: 'Caua Henrique da Costa Camara',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 7,
          name: 'Caio Victor Carioca Camara',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 7,
          name: 'Ritha Beatriz Carioca Camara',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 8,
          name: 'Augustinha Farias da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 8,
          name: 'Edilson Farias da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 8,
          name: 'Claudia Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 9,
          name: 'Frank Wilson Camara da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 9,
          name: 'Ana Luiza da Silva Lisboa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 9,
          name: 'José Lucio Antony Lisboa Camara',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 10,
          name: 'Daniel Cilas Batista Bindá',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 10,
          name: 'Samuel Cilas Batista Bindá',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 10,
          name: 'Cilas da Mota Bindá',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 11,
          name: 'Maria Alcicleide Batista da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 11,
          name: 'Felipe da Silva Lima',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 11,
          name: 'Maria do Carmo da Silva Batista',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 12,
          name: 'Ian Gustavo Alves Pessoa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 13,
          name: 'Feliph Kevin Gonçalves Mota',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 14,
          name: 'Lennon Brandão Freitas do Nascimento',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 15,
          name: 'Evaldo Patrik dos Santos Cardoso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 16,
          name: 'João Pedro Ferreira Furquim Souza',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 17,
          name: 'Maicon Wellington Pantoja de Souza',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 18,
          name: 'Luiz Osmar Augusto Cunha Ruiz',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 19,
          name: 'Wesley da Silva Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 20,
          name: 'William Azevedo da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 21,
          name: 'Levi da Silva Lima',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 22,
          name: 'Francisco Helio Parente Arcos Filho',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 22,
          name: 'Leticia Martins Vieira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 23,
          name: 'Alison Soares de Almeida',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 23,
          name: 'Ana Paula Salles Guerreiro de Almeida',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 24,
          name: 'Arlley Gabriel Dias e Dias',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 25,
          name: 'Matheus de Oliveira Assunção',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 26,
          name: 'Vitor Norton de Lima Azevedo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 27,
          name: 'Italo Tony da Costa Alves',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 28,
          name: 'Ruan Carlos Mota Teixeira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 29,
          name: 'Rubens Andrade Fernandes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 30,
          name: 'Samuel Bruno Torres Rêgo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 31,
          name: 'Fábio de Sousa Cardoso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 31,
          name: 'Jacinta Lima Rogério Cardoso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 31,
          name: 'Isabela Rogério Cardoso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 31,
          name: 'Nicole Rogério Cardoso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 32,
          name: 'Jeferson da Silva Ferreira ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 32,
          name: 'Tayane Félix da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 33,
          name: 'Andreza Magalhães Hipolito',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 33,
          name: 'Gillyard Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 34,
          name: 'Fábio Costa Coelho da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 34,
          name: 'Bianca Lima Queiroz Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 35,
          name: 'Fábio Wendel Araújo Serrão',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 36,
          name: 'Ivan Lucas Moreira Rodrigues ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 37,
          name: 'Thiago Souza da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 38,
          name: 'Gabriel Lima Damião',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 39,
          name: 'Tassiano Carvalho dos Santos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 39,
          name: 'Maria de Lourdes Carvalho dos Santos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 39,
          name: 'Tadeu Rocha dos Santos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 40,
          name: 'Vitor Henrique Lima Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 41,
          name: 'Raibemar Gomes Benevides',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 44,
          name: 'Matheus Ramos de Lima',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 45,
          name: 'Mauryen Oliveira Araújo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 45,
          name: 'Daniel Lima Araújo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 45,
          name: 'Ana Júlia Oliveira Araújo',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 42,
          name: 'Piter Douglas de Sousa Diniz',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 42,
          name: 'Janaína Gonçalves Diniz',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 42,
          name: 'Kamilly Beatriz Freitas Diniz',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 42,
          name: 'Julia Gonçalves Diniz',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 43,
          name: 'Mariana Luzia Elias Camarate',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 43,
          name: 'Thiago Vital Leite Camarate',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 46,
          name: 'Flavio Raimundo Lessa Filho',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 46,
          name: 'Andreia Pardo Lessa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 46,
          name: 'Hendrew Pardo Lessa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 46,
          name: 'Flavia Alessandra da Silva Lessa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 46,
          name: 'Andrey Pardo Lessa',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 47,
          name: 'Fany Regina Braga Simão',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 47,
          name: 'Isaac José Simão Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 48,
          name: 'Dalva Nazare Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 48,
          name: 'Carlos Moreira de Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 48,
          name: 'Marcelo Nazare Moraes ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 48,
          name: 'Rodrigo Nazare Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 49,
          name: 'Renan Nazare Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 49,
          name: 'Sarah Real Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 49,
          name: 'Lara Real Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 49,
          name: 'Theo Real Moraes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 49,
          name: 'Caio Real Moraes ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 50,
          name: 'Virgilio Teixeira Cunha Filho',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 50,
          name: 'Candida Berger Reis',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 50,
          name: 'Vilane Reis Cunha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 50,
          name: 'Virlene Reis Cunha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 50,
          name: 'Virginia Reis Cunha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 51,
          name: 'Eluma Ellen Carvalho Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 51,
          name: 'Alan Souza Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 52,
          name: 'Pamela Andreia da Silva Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 52,
          name: 'Alberta Silva do Nascimento ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 53,
          name: 'Kaylane Karina Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 54,
          name: 'Rebeca Lucas Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 55,
          name: 'Adriana Nascimento da Mata',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 56,
          name: 'Kamylla Oliveira Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 56,
          name: 'Edson Bruno Guimarães de Almeida',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 57,
          name: 'Marluce Nery de Oliveira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 57,
          name: 'Alex de Souza Pardo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 58,
          name: 'Silvia Meneses de Arruda Freitas',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 58,
          name: 'Daniel dos Santos Freitas',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 59,
          name: 'Hileia Nazare Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 59,
          name: 'Eduardo Nazare Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 60,
          name: 'Dayane Karoline Alves da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 60,
          name: 'Vinicius Cabral Lopes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 61,
          name: 'Yago Ono de Souza Moreira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 62,
          name: 'Leonardo Martins Pessoa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 63,
          name: 'Kethlen Mendes Caetano',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 64,
          name: 'Maria Eduarda Lima da Silva',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 64,
          name: 'Leandro de Souza Bezerra',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 65,
          name: 'Thayná Bulcão Péres',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 65,
          name: 'Erick Johnson Gama Araújo',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 66,
          name: 'Raphael de Souza Nunes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 66,
          name: 'Luana Nascimento Vicente',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 67,
          name: 'Andreia Nasare da Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 68,
          name: 'Nicole Kelly Cortesão',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 68,
          name: 'Lucas André Cordeiro da Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 69,
          name: 'Aécio de Souza Leite Neto',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 70,
          name: 'Natan Alexandre Cruz Corado',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 71,
          name: 'Giovanna Carvalho Nunes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 72,
          name: 'Rayssa Vinhote dos Santos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 73,
          name: 'Itala Pereira Correa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 74,
          name: 'Rayana Lima Cintra',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 75,
          name: 'Ariana da Cunha Gama Brandão',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 75,
          name: 'Helbran Batista Brandão',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 75,
          name: 'Ana Luíza Gama Brandão ',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 76,
          name: 'Laisa Hidemi Alves Oka',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 77,
          name: 'Estefany Gabriela Cruz Vasconcelos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 77,
          name: 'Diogo Costa Lima',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 78,
          name: 'Alice Roberta Barbosa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 78,
          name: 'Thiago dos Santos Leal',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 79,
          name: 'Viviane Santos Afonso',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 80,
          name: 'Luana Victória Machado',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 81,
          name: 'Thayanny Guimarães Ferreira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 82,
          name: 'Liliane Pereira de Menezes',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 83,
          name: 'Roberjane Silva Castro',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 84,
          name: 'Tiago Ramos de Sá',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 84,
          name: 'Dayanne Barros Rocha de Mesquita',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 85,
          name: 'Ana Clara Begnini',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 85,
          name: 'Vinicius Pinheiro',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 86,
          name: 'Marcus Vinicius Bezerra da  Cunha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 87,
          name: 'Eduardo Arce Sales ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 88,
          name: 'Itailb Lamarão Vilas Boas ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 89,
          name: 'Dionelia Oliveira Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 89,
          name: 'Valdiberto Ribeiro Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 89,
          name: 'Victor Efrain Oliveira Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 90,
          name: 'Maria do Perpétuo Socorro Oliveira ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 90,
          name: 'Amaury Ferreira de Oliveira',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 91,
          name: 'Lucimar Batista da Silva ',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 92,
          name: 'Mara Perpetua da Silva Gaspar',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 92,
          name: 'Rozival Silva de Freitas',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 93,
          name: 'Dilair Nazare Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 93,
          name: 'Esposo Dilair',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 94,
          name: 'Deiva Maria Nazare da Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 94,
          name: 'Gliceria Maria Nazare da Rocha',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 94,
          name: 'Damares da Rocha Santos',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          family_id: 94,
          name: 'Adail Eduarda da Rocha Costa',
          is_confirmed: null,
          is_present: null,
          is_child: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    ),

  down: queryInterface => queryInterface.bulkDelete('guests', null, {}),
};
